### ISSUE TITLE
Start TODO

### ISSUE THREAD

**Issue by INeedJobToStartWork** [INeedJobToStartWork/DarkUI#3]
Zrób Liste Wszystkich Componentów do zrobienia.
Pogrupuj je na 2 Grupy

- Atoms and Molecules
- Organisms

**1. Atoms and Molecules** - Podstawowe Componenty składowe i złożone Typu **Button**, **Input (I jego rodzaje)** etc.
**2. Organisms** - Componenty złożone z **Molecules**  typu **Navigation bar**, **Footer** etc.

Liste zrób z Checkboxami typu

### Atoms and Molecules ⚛️
------------

- [ ] Buttons
- [ ] Inputs

### Organism 🧬
------------

- [ ] Navigation
- [ ] Footer

Lista Design Systemów z których masz wypisać wszystkie componenty na tamte 2 kategorie (Dla Łatwiejszej późniejszej pracy możesz zlinkować skąd wziąłeś component):

- [ ] [Boltdesignsystem](https://boltdesignsystem.com/pattern-lab/)
- [ ] [Wanda Design](https://design.wonderflow.ai/get-started/components/actions/button)
- [ ] [Biings DS](https://biings.design/#/)
- [ ] [Cbrebuild]( https://blocks.cbrebuild.com/components/buttons/)
- [ ] [Fusionfabric](https://design.fusionfabric.cloud/components)
- [ ] [OrbitKiwi](https://orbit.kiwi/getting-started/)
- [ ] [Bulb](https://design.bulb.co.uk//)
- [ ] [Vercel](https://vercel.com/design/brands) 
- [ ] [Wonderbly](http://design-system.wonderbly.com/components/atoms/Badge)
- [ ] [Yoga](https://gympass.github.io/yoga/components/getting-started)
- [ ] [Vanilla FrameWork](https://vanillaframework.io/docs)
- [ ] [NextUI](https://nextui.org/docs/components/avatar)
- [ ] [VueSax](https://vuesax.com/docs/guide/)
